## This error is raised when an invalid url is placed in the scanner tab
## A better way to handle it will be to show an alert that the endpoint was incorret


Exception in thread Thread-2:Traceback (most recent call last):
  File "/var/folders/bc/1cx_772j0bv1d3pfgf9hrwq40000gn/T/burp8670850635644946499.tmp/2/Lib/threading.py", line 222, in _Thread__bootstrap
    self.run()
  File "/var/folders/bc/1cx_772j0bv1d3pfgf9hrwq40000gn/T/burp8670850635644946499.tmp/2/Lib/threading.py", line 213, in run
    self._target(*self._args, **self._kwargs)
  File "__pyclasspath__/inql/utils.py", line 237, in async_run
    execute()
  File "__pyclasspath__/inql/widgets/generator.py", line 325, in async_run
    init(AttrDict(args.copy()))
  File "__pyclasspath__/inql/introspection.py", line 285, in init
    argument = json.loads(argument)
  File "/var/folders/bc/1cx_772j0bv1d3pfgf9hrwq40000gn/T/burp8670850635644946499.tmp/2/Lib/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/var/folders/bc/1cx_772j0bv1d3pfgf9hrwq40000gn/T/burp8670850635644946499.tmp/2/Lib/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/var/folders/bc/1cx_772j0bv1d3pfgf9hrwq40000gn/T/burp8670850635644946499.tmp/2/Lib/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

